apiVersion: v1
kind: Service
metadata:
  name: dira-front
  namespace: {{ .Release.Namespace }}
  labels:
    app: dira-front
spec:
  type: NodePort
  selector:
    app: dira-front
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.frontend.nodePort }}
