apiVersion: apps/v1
kind: Deployment
metadata:
  name: dira-infer
  namespace: mlrun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dira-infer
  template:
    metadata:
      labels:
        app: dira-infer
    spec:
      containers:
        - name: dira-infer
          image: dira-infer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: /model/modelo_diabetes_DIRA.pkl
          volumeMounts:
            - name: model
              mountPath: /model
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: model
          persistentVolumeClaim:
            claimName: model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dira-infer
  namespace: mlrun
spec:
  type: NodePort
  selector:
    app: dira-infer
  ports:
    - port: 8000
      targetPort: 8000
